header:
  license:
    spdx-id: AGPL-3.0-or-later
    copyright-owner: Genome Research Ltd
    copyright-year: '2022-2050'

  paths:
    - '**'

  paths-ignore:
    - '.circleci'
    - '.dockerignore'
    - '.gitignore'
    - 'CHANGES.md'
    - 'Dockerfile'
    - 'LICENSE'
    - 'Makefile'
    - 'README.md'
    - 'EXAMPLE'
    - 'main.nf'
    - 'nextflow.config'
    - '**/*.yaml'
    - 'src/bamcov.c'
    - 'src/sam_opts.*'
    - 'src/samtools.*'
    - 'src/sam_utils.*'
    - 'test/*'
    - 'LSF/*'
    - 'Nextflow/**'

  comment: on-failure
